### ISSUE TITLE
5 feedbacks

### ISSUE THREAD

**Issue by jokerkeny** [mavam/stat-cookbook#21]
In
## 2 Probability Theory
* Probability Distribution P
<a href="https://www.codecogs.com/eqnedit.php?latex=\Bbb&space;P\left[\bigcup_{i=1}^\infty&space;A_i&space;\right]=\sum_{i=1}^\infty&space;\Bbb&space;P&space;[A_i]" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Bbb&space;P\left[\bigcup_{i=1}^\infty&space;A_i&space;\right]=\sum_{i=1}^\infty&space;\Bbb&space;P&space;[A_i]" title="\Bbb P\left[\bigcup_{i=1}^\infty A_i \right]=\sum_{i=1}^\infty \Bbb P [A_i]" /></a>
A_i should be disjoint here.

In
* Inclusion-Exclusion Principle
the subscript of the sum should be
1<=i_1<...<i_r<=n
instead of starting at i

In
### 3.1 Transformation
Convolution
* Z:=X/Y, there is an additional f_x(x) at last
(What's more, are product and difference convolution? I'm not sure)

In
## 4 Expectation
* E[XY]=...
Should it be dxdy? maybe it mixes the independent case?

What's more, I tried mingw32-make in windows,(hmm, I'm newbie about Github & Linux) and it's exhausted to update my TeX and solve the compile error, which took me 2 hrs. However, I can't solve it in windows. I can compile out the major but without the contents. 
At last, I tried msys(MinGW, a simulated Linux environment in windows). Everything just solved...
Maybe you can add this to the readme.

**Comment by mavam** [comment]
Thanks for your suggestion. Which version of the cookbook are you using? Some of your comments appear to apply to an older version. To address your points, in order:

1. Already fixed in the most recent version.
2. I'm using the indices as in [Wikipedia page](https://en.wikipedia.org/wiki/Inclusion–exclusion_principle), with *r=|J|*.
3. Fixed as of #20.
4. When two random variables are statistically independent, the expectation of their product is the product of their expectations. I think the current formula correctly describes this fact. For notational convenience, I use *dF_X(x)* to denote both the discrete and continuous case. See the first formula in §4.
